apiVersion: v1
kind: Service
metadata:
  name: nimbus-gateway-external
  labels:
    app: nimbus-gateway
spec:
  type: NodePort
  selector:
    app: nimbus-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
    - name: metrics
      port: 9090
      targetPort: metrics
      nodePort: 30090
